import { Game, User, Review, GameList, GameEntry } from "@/types";

export const mockGames: Game[] = [
  {
    id: "1",
    slug: "the-last-of-us-part-ii",
    title: "The Last of Us Part II",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc4xrf.jpg",
    releaseYear: 2020,
    developer: "Naughty Dog",
    publisher: "Sony Interactive Entertainment",
    platforms: ["PS4", "PS5"],
    genres: ["Action", "Adventure"],
    summary: "Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming. Living amongst a thriving community of survivors has allowed them peace and stability, despite the constant threat of the infected and other, more desperate survivors.",
    igdbRating: 88,
    communityRating: 4.2,
    ratingCount: 42381,
  },
  {
    id: "2",
    slug: "elden-ring",
    title: "Elden Ring",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc8fy5.jpg",
    releaseYear: 2022,
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    genres: ["RPG", "Action"],
    summary: "Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    igdbRating: 96,
    communityRating: 4.7,
    ratingCount: 89234,
  },
  {
    id: "3",
    slug: "god-of-war-ragnarok",
    title: "God of War Ragnarök",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9lx2.jpg",
    releaseYear: 2022,
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    platforms: ["PS4", "PS5"],
    genres: ["Action", "Adventure"],
    summary: "Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.",
    igdbRating: 94,
    communityRating: 4.5,
    ratingCount: 67123,
  },
  {
    id: "4",
    slug: "cyberpunk-2077",
    title: "Cyberpunk 2077",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4hk6.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7ywh.jpg",
    releaseYear: 2020,
    developer: "CD Projekt Red",
    publisher: "CD Projekt",
    platforms: ["PC", "PS4", "PS5", "Xbox"],
    genres: ["RPG", "Action"],
    summary: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification.",
    igdbRating: 86,
    communityRating: 3.9,
    ratingCount: 55678,
  },
  {
    id: "5",
    slug: "red-dead-redemption-2",
    title: "Red Dead Redemption 2",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc4xrh.jpg",
    releaseYear: 2018,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    platforms: ["PC", "PS4", "Xbox"],
    genres: ["Action", "Adventure"],
    summary: "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.",
    igdbRating: 97,
    communityRating: 4.8,
    ratingCount: 103456,
  },
  {
    id: "6",
    slug: "hollow-knight",
    title: "Hollow Knight",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rgi.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc4xrl.jpg",
    releaseYear: 2017,
    developer: "Team Cherry",
    publisher: "Team Cherry",
    platforms: ["PC", "Switch", "PS4", "Xbox"],
    genres: ["Metroidvania", "Action"],
    summary: "A challenging 2D action-adventure. Forge your own path through an enormous underground kingdom of insects and heroes, ancient mysteries and lethal danger.",
    igdbRating: 90,
    communityRating: 4.6,
    ratingCount: 34567,
  },
  {
    id: "7",
    slug: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6ly7.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc9lx3.jpg",
    releaseYear: 2023,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    platforms: ["PC", "PS5"],
    genres: ["RPG", "Strategy"],
    summary: "An ancient evil has returned to Baldur's Gate, intent on devouring it from the inside out. The fate of Faerûn lies in your hands.",
    igdbRating: 96,
    communityRating: 4.9,
    ratingCount: 78901,
  },
  {
    id: "8",
    slug: "hades",
    title: "Hades",
    coverUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ekt.jpg",
    backdropUrl: "https://images.igdb.com/igdb/image/upload/t_screenshot_big/sc7ywi.jpg",
    releaseYear: 2020,
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    platforms: ["PC", "Switch", "PS4", "PS5", "Xbox"],
    genres: ["Roguelike", "Action"],
    summary: "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    igdbRating: 93,
    communityRating: 4.6,
    ratingCount: 45678,
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    username: "albavxs",
    email: "alba@example.com",
    displayName: "Alba",
    bio: "Gamer apaixonada por RPGs e jogos indie. Platinadora compulsiva.",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alba",
    location: "São Paulo, BR",
    website: "https://albavxs.dev",
    createdAt: "2023-01-15T00:00:00Z",
    gamesPlayed: 247,
    gamesThisYear: 34,
    followersCount: 128,
    followingCount: 89,
  },
  {
    id: "2",
    username: "gamer_pro",
    email: "gamer@example.com",
    displayName: "GameMaster",
    bio: "Speedrunner e crítico de jogos. Especialista em soulslike.",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=gamer",
    location: "Rio de Janeiro, BR",
    createdAt: "2023-03-20T00:00:00Z",
    gamesPlayed: 512,
    gamesThisYear: 67,
    followersCount: 342,
    followingCount: 156,
  },
  {
    id: "3",
    username: "indie_lover",
    email: "indie@example.com",
    displayName: "Indie Lover",
    bio: "Amante de jogos independentes e narrativas únicas.",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=indie",
    location: "Curitiba, BR",
    createdAt: "2023-06-10T00:00:00Z",
    gamesPlayed: 189,
    gamesThisYear: 28,
    followersCount: 67,
    followingCount: 43,
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    userId: "2",
    gameId: "2",
    rating: 5,
    content: "Uma obra-prima absoluta. FromSoftware superou todas as expectativas com Elden Ring. O mundo aberto é vasto e cheio de segredos, cada canto tem algo novo para descobrir. A dificuldade é justa e recompensadora. Simplesmente o melhor jogo dos últimos anos.",
    containsSpoiler: false,
    playedDate: "2022-04-15T00:00:00Z",
    createdAt: "2022-04-20T00:00:00Z",
    updatedAt: "2022-04-20T00:00:00Z",
    user: mockUsers[1],
    game: mockGames[1],
    likesCount: 234,
    commentsCount: 18,
  },
  {
    id: "2",
    userId: "1",
    gameId: "7",
    rating: 4.5,
    content: "Baldur's Gate 3 é uma experiência incrível. A profundidade das escolhas e consequências é impressionante. Cada playthrough é completamente diferente. Larian Studios entregou o RPG definitivo da geração.",
    containsSpoiler: false,
    playedDate: "2023-09-01T00:00:00Z",
    createdAt: "2023-10-05T00:00:00Z",
    updatedAt: "2023-10-05T00:00:00Z",
    user: mockUsers[0],
    game: mockGames[6],
    likesCount: 156,
    commentsCount: 12,
  },
  {
    id: "3",
    userId: "3",
    gameId: "6",
    rating: 5,
    content: "Hollow Knight é a prova de que jogos indie podem superar qualquer AAA. Arte deslumbrante, trilha sonora épica, gameplay desafiador e uma lore profundíssima. Team Cherry criou uma obra-prima atemporal.",
    containsSpoiler: false,
    playedDate: "2023-07-20T00:00:00Z",
    createdAt: "2023-07-25T00:00:00Z",
    updatedAt: "2023-07-25T00:00:00Z",
    user: mockUsers[2],
    game: mockGames[5],
    likesCount: 89,
    commentsCount: 7,
  },
  {
    id: "4",
    userId: "2",
    gameId: "5",
    rating: 5,
    content: "Red Dead Redemption 2 é o pico do storytelling em jogos. Arthur Morgan é um dos personagens mais bem escritos da história dos videogames. Rockstar criou um mundo vivo e respirante que nunca mais vi igual.",
    containsSpoiler: false,
    playedDate: "2022-12-10T00:00:00Z",
    createdAt: "2022-12-15T00:00:00Z",
    updatedAt: "2022-12-15T00:00:00Z",
    user: mockUsers[1],
    game: mockGames[4],
    likesCount: 312,
    commentsCount: 24,
  },
];

export const mockLists: GameList[] = [
  {
    id: "1",
    userId: "1",
    title: "Os Melhores RPGs de Todos os Tempos",
    description: "Uma seleção cuidadosa dos RPGs que definiram o gênero e deixaram sua marca na história dos videogames.",
    isPublic: true,
    createdAt: "2023-08-01T00:00:00Z",
    user: mockUsers[0],
    likesCount: 234,
    gamesCount: 15,
  },
  {
    id: "2",
    userId: "2",
    title: "Soulslike Essenciais",
    description: "Do mais fácil ao mais brutal — guia completo para quem quer entrar no gênero.",
    isPublic: true,
    createdAt: "2023-09-15T00:00:00Z",
    user: mockUsers[1],
    likesCount: 189,
    gamesCount: 12,
  },
  {
    id: "3",
    userId: "3",
    title: "Joias Escondidas do Indie",
    description: "Jogos independentes que merecem muito mais reconhecimento do que receberam.",
    isPublic: true,
    createdAt: "2023-11-20T00:00:00Z",
    user: mockUsers[2],
    likesCount: 145,
    gamesCount: 20,
  },
];

export const mockGameEntries: GameEntry[] = [
  {
    id: "1",
    userId: "1",
    gameId: "7",
    status: "PLAYED",
    rating: 4.5,
    playedDate: "2023-09-01T00:00:00Z",
    createdAt: "2023-10-05T00:00:00Z",
    updatedAt: "2023-10-05T00:00:00Z",
    game: mockGames[6],
  },
  {
    id: "2",
    userId: "1",
    gameId: "2",
    status: "PLAYED",
    rating: 5,
    playedDate: "2022-04-15T00:00:00Z",
    createdAt: "2022-04-20T00:00:00Z",
    updatedAt: "2022-04-20T00:00:00Z",
    game: mockGames[1],
  },
  {
    id: "3",
    userId: "1",
    gameId: "3",
    status: "PLAYING",
    playedDate: undefined,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
    game: mockGames[2],
  },
  {
    id: "4",
    userId: "1",
    gameId: "4",
    status: "WISHLIST",
    playedDate: undefined,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
    game: mockGames[3],
  },
];

export const ratingHistogram = [
  { rating: 5, count: 12430, percentage: 28 },
  { rating: 4.5, count: 9876, percentage: 22 },
  { rating: 4, count: 11234, percentage: 25 },
  { rating: 3.5, count: 5678, percentage: 13 },
  { rating: 3, count: 3456, percentage: 8 },
  { rating: 2.5, count: 1234, percentage: 3 },
  { rating: 2, count: 456, percentage: 1 },
  { rating: 1, count: 123, percentage: 0 },
];
